# POST http://localhost:3000/api/blog/create
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZWE5OWY1OTFiOTQ3MGNjOTJkZmU3YiIsImlhdCI6MTcwOTkxODQyOSwiZXhwIjoxNzA5OTIyMDI5fQ.b2MZQ13dVRL7Kl-gYvDrskmeiGSNZX1eNpMLwmceutc
# Content-Type: application/json

# {
#     "title" : "My first blog",
#     "banner" : "https://google.com/image.png",
#     "content" : [
#         {
#             "type" : "text",
#             "data" : "This is my first blog. I am so excited to write this blog. I hope you will like it."
#         }
#     ],
#     "des" : "This is my first blog. I am so excited to write this blog. I hope you will like it.",
#     "tags" : ["blog"]
# }

# GET http://localhost:3000/api/blog/trending

# POST http://localhost:3000/api/blog/search-blogs
# Content-Type: application/json

# {
#     "tag" : "blog"
# }

# POST http://localhost:3000/api/user/search
# Content-Type: application/json

# {
#     "query" : "dev.m"
# }

# POST http://localhost:3000/api/user/get-profile
# Content-Type: application/json

# {
#     "userId" : "dev.mohit2006"
# } 

# POST http://localhost:3000/api/blog/get-blog
# Content-Type: application/json

# {
#     "blog_id" : "About-user-not-found-pageEKBm56EROj1soOj9Tt5sY"
# }

# POST http://localhost:3000/api/blog/verify-blog
# Content-Type: application/json
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZjJiZjE5OWJlYjhlYTkyMmNhYzQ3ZCIsImlhdCI6MTcxMDQxMTEyMywiZXhwIjoxNzEwNDI5MTIzfQ.AQo_wj5JVKFAhAtQBOKx8HEtFKRLjy6qt2Y3qvVYhnw

# {
#     "blog_id" : "The-Art-of-Images-Power-Perception-and-the-Visual-WorldOufoILgl0F--cpt2ofGU9"
# }

POST http://localhost:3000/api/blog/like-blog
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZjJlZmI4YmIwM2FiMjAzYjM2NTRhZiIsImlhdCI6MTcxMDQ4MDU2NiwiZXhwIjoxNzEwNDk4NTY2fQ.Lzi33S0V2LHL-SUFJ89Pw4sD5VfbKNUjINWklWD7NNM
Content-Type: application/json

{
    "blog_id" : "The-Power-of-Unity-Strength-in-TogethernessqgFiGWLt1K9B2-IPrIwvj",
    "is_liked_by_user" : false
}